[package]
name = "mainstage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plist = "1.1.0"
serde = "1"
thiserror = "1.0"